### ISSUE TITLE
UploadedFile::fake() error

### ISSUE THREAD

**Issue by kszyrvercobrador** [lorisleiva/laravel-docker#43] opened 2019-11-20 07:09 UTC
It will give this error when using UploadedFile::fake()->image('avatar.png') in testing

`testing.ERROR: Call to undefined function Intervention\Image\Gd\imagejpeg()`

**Comment by lorisleiva** [comment] 2019-11-20 08:47
Hi, thanks for sharing. I'm fairly confident this is because of #21.

I'll mark that as a duplicate in order to keep all information in one thread.

Duplicate of #21

**Closed by lorisleiva** 2019-11-20 08:47 UTC
